#!/bin/bash

# This must match the install directory.
INSTALL=/usr/local/introcs

# Sets the path to the textbook libraries.
CLASSPATH=(.:stdlib.jar)

# Execute with textbook libraries in Java classpath.
java -cp "${CLASSPATH}" "$@"
